name: civitai_api
description: A comprehensive, production-ready Dart client for the CivitAI API, providing complete type-safe access to all endpoints.
version: 1.0.0
homepage: https://github.com/yourusername/civitai_api
repository: https://github.com/yourusername/civitai_api
issue_tracker: https://github.com/yourusername/civitai_api/issues

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^1.0.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.22.0